# Generated by Django 2.2.3 on 2019-08-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190813_0238'),
        ('Categories', '0002_auto_20190813_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='subcategory2',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.SubCategory1'),
        ),
        migrations.AddField(
            model_name='subcategory1',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.MainCategory'),
        ),
    ]
