# Generated by Django 2.2.3 on 2019-08-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_auto_20190813_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
