# Generated by Django 2.2.3 on 2019-08-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0004_allcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
