# Generated by Django 2.2.3 on 2019-08-13 00:32

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('highlight', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Images', models.ImageField(blank=True, null=True, upload_to=products.models.new_image_path)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='Categories.Category')),
                ('secondsub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondsub', to='Categories.Category')),
                ('thirdsub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdsub', to='Categories.Category')),
            ],
        ),
    ]
