# Generated by Django 2.2.3 on 2019-08-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_auto_20190813_0238'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondsub',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thirdsub',
        ),
        migrations.AddField(
            model_name='product',
            name='MainCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='Categories.MainCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='SubCategory1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub1', to='Categories.SubCategory1'),
        ),
        migrations.AddField(
            model_name='product',
            name='SubCategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub2', to='Categories.SubCategory2'),
        ),
    ]
