# Generated by Django 2.2.3 on 2019-08-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='express',
            field=models.BooleanField(default=False),
        ),
    ]
