# Generated by Django 2.2.3 on 2019-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_videofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorANDSizeANDQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=120)),
                ('Color', models.CharField(max_length=120)),
                ('Quantity', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='videofile',
        ),
        migrations.AddField(
            model_name='product',
            name='CSQ',
            field=models.ManyToManyField(blank=True, null=True, to='products.ColorANDSizeANDQuantity'),
        ),
    ]
