# Generated by Django 2.2.3 on 2019-08-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190817_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CSQ',
        ),
        migrations.AddField(
            model_name='product',
            name='CSQ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ColorANDSizeANDQuantity'),
        ),
    ]
