# Generated by Django 2.2.3 on 2019-08-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190817_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CSQ',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ColorANDSizeANDQuantity'),
        ),
    ]
